steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/stoked-elixir-242309/bono-test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/stoked-elixir-242309/bono-test'] 
